myrecommendations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myrestaurants/', include('myrestaurants.urls', namespace='myrestaurants')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })
    ]

myrestaurants/urls.py
from django.conf.urls import url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from models import Restaurant, Dish
from forms import RestaurantForm, DishForm
from views import RestaurantCreate, DishCreate, RestaurantDetail, review, TotalData

urlpatterns = [
    # List latest 5 restaurants: /myrestaurants/
    url(r'^$',
        ListView.as_view(
            queryset=Restaurant.objects.filter(date__lte=timezone.now()).order_by('date')[:5],
            context_object_name='latest_restaurant_list',
            template_name='myrestaurants/restaurant_list.html'),
        name='restaurant_list'),

    # dashboard
    url(r'^dashboard/',
        TotalData.as_view(),
     name='dashboard'),

    # Restaurant details, ex.: /myrestaurants/restaurants/1/
    url(r'^restaurants/(?P<pk>\d+)/$',
        RestaurantDetail.as_view(),
        name='restaurant_detail'),

    # Restaurant dish details, ex: /myrestaurants/restaurants/1/dishes/1/
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Dish,
            template_name='myrestaurants/dish_detail.html'),
        name='dish_detail'),

    # Create a restaurant, /myrestaurants/restaurants/create/
    url(r'^restaurants/create/$',
        RestaurantCreate.as_view(),
        name='restaurant_create'),

    # Edit restaurant details, ex.: /myrestaurants/restaurants/1/edit/
    url(r'^restaurants/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Restaurant,
            template_name='myrestaurants/form.html',
            form_class=RestaurantForm),
        name='restaurant_edit'),

    # Create a restaurant dish, ex.: /myrestaurants/restaurants/1/dishes/create/
    url(r'^restaurants/(?P<pk>\d+)/dishes/create/$',
        DishCreate.as_view(),
        name='dish_create'),

    # Edit restaurant dish details, ex.: /myrestaurants/restaurants/1/dishes/1/edit/
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Dish,
            template_name='myrestaurants/form.html',
            form_class=DishForm),
        name='dish_edit'),

    # Create a restaurant review, ex.: /myrestaurants/restaurants/1/reviews/create/
    url(r'^restaurants/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),
]

myrestaurants/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date

class Restaurant(models.Model):
    name = models.TextField()
    street = models.TextField(blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    city = models.TextField(default="")
    zipCode = models.TextField(blank=True, null=True)
    stateOrProvince = models.TextField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)
    telephone = models.TextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myrestaurants:restaurant_detail', kwargs={'pk': self.pk})


class Dish(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField('Euro amount', max_digits=8, decimal_places=2, blank=True,
        null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)
    image = models.ImageField(upload_to="myrestaurants", blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, null=True, related_name='dishes')

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myrestaurants:dish_detail', kwargs={'pkr': self.restaurant.pk, 'pk': self.pk})

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant)

myrestaurants/forms.py
from django.forms import ModelForm
from models import Restaurant, Dish

class RestaurantForm(ModelForm):
  class Meta:
    model = Restaurant
    exclude = ('user', 'date',)

class DishForm(ModelForm):
  class Meta:
    model = Dish
    exclude = ('user', 'date', 'restaurant',)

myrestaurants/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView,ListView
from django.views.generic.edit import CreateView
from django.db.models import Count
from models import RestaurantReview, Restaurant, Dish
from forms import RestaurantForm, DishForm


class RestaurantDetail(DetailView):
  model = Restaurant
  template_name = 'myrestaurants/restaurant_detail.html'

  def get_context_data(self, **kwargs):
    context = super(RestaurantDetail, self).get_context_data(**kwargs)
    context['RATING_CHOICES'] = RestaurantReview.RATING_CHOICES
    return context

class RestaurantCreate(CreateView):
  model = Restaurant
  template_name = 'myrestaurants/form.html'
  form_class = RestaurantForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(RestaurantCreate, self).form_valid(form)

class DishCreate(CreateView):
  model = Dish
  template_name = 'myrestaurants/form.html'
  form_class = DishForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    form.instance.restaurant = Restaurant.objects.get(id=self.kwargs['pk'])
    return super(DishCreate, self).form_valid(form)

def review(request, pk):
  restaurant = get_object_or_404(Restaurant, pk=pk)
  review = RestaurantReview(
      rating=request.POST['rating'],
      comment=request.POST['comment'],
      user=request.user,
      restaurant=restaurant)
  review.save()
  return HttpResponseRedirect(reverse('myrestaurants:restaurant_detail', args=(restaurant.id,)))

class TotalData(ListView):
    template_name = 'myrestaurants/dashboard.html'

    def get_queryset(self):
        return Restaurant.objects.all().count

    def get_context_data(self, **kwargs):
        context = super(TotalData, self).get_context_data(**kwargs)
        context['num_resto'] = Restaurant.objects.all().count
        context['num_dish'] = Dish.objects.all().count
        context['num_review'] = RestaurantReview.objects.all().count
        context['num_reviewer'] = RestaurantReview.objects.values('user_id').distinct().count()
        return context

myrestaurants/templates/myrestaurants/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "style/base.css" %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>{% block title %}MyRestaurants{% endblock %}</title>
</head>
<body>
<div id="header">
    <div class="logo">
      My Restaurant
    </div>
    {% block header %}
        {% if user.username %}
            <p>User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p>Have an account? <a href="{% url 'login' %}?next={{request.path}}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;login</a></p>{% endif %}
    {% endblock %}
</div>
<div id="datacontent">
<div id="sidebar">
    {% block sidebar %}
    <ul class="menu">
    <a href="/myrestaurants/dashboard">
      <li><i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard</li>
    </a>
      <a href="/myrestaurants">
        <li><i class="fa fa-home" aria-hidden="true"></i> Home</li>
      </a>
  </ul>{% endblock %}
</div>
<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>
</div>
<div id="footer">Created by Razinal Rahmat</div>
</body>
</html>

myrestaurants/templates/myrestaurants/dashboard.html
{% extends "myrestaurants/base.html" %}

{% block content %}

<h1>
    <i class="fa fa-bars" aria-hidden="true"></i> Total Data
</h1>
<hr>
<div class="_d">
<ul class="list">
              <li>
                Restaurant: {{ num_resto }}
              </li>
              <li>
                Total Dish: {{ num_dish }}
              </li>
              <li>
                Total Review: {{ num_review }}
              </li>
              <li>
                Reviewer: {{ num_reviewer }}
              </li>


</ul>
</div>
{% endblock %}

{% block footer %}
    Created by {{ dish.user }} on {{ dish.date }}
{% endblock %}

myrestaurants/templates/myrestaurants/dish_detail.html
{% extends "myrestaurants/base.html" %}

{% block content %}

<h1>
    <i class="fa fa-cutlery" aria-hidden="true"></i> {{ dish.name }}
    {% if user == dish.user %}
        <div class="pullright">
          <a href="{% url 'myrestaurants:dish_edit' dish.restaurant.id dish.id %}">
            <i class="fa fa-edit" aria-hidden="true"></i> edit</a>
        </div>
    {% endif %}
</h1>
<hr>
<div class="_d">
<p>{{ dish.description }}</p>
{% if dish.image %}
    <div class="_i_d"><img src="{{ dish.image.url }}"/></div>
{% endif %}
<p class="_s">Served by <a href="{% url 'myrestaurants:restaurant_detail' dish.restaurant.id %}">{{ dish.restaurant.name }}</a></p>
</div>
<hr>

<a class="back" href="{{request.META.HTTP_REFERER}}"><i class="fa fa-undo" aria-hidden="true"></i> Go back</a>
<div style="margin-bottom:10px"></div>
{% endblock %}

{% block footer %}
    Created by {{ dish.user }} on {{ dish.date }}
{% endblock %}

myrestaurants/templates/myrestaurants/form.html
{% extends "myrestaurants/base.html" %}
{% block content %}
  <h1>
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add data
  </h1>
  <hr>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <a class="back" href="{{request.META.HTTP_REFERER}}"><i class="fa fa-undo" aria-hidden="true"></i> Go back</a>
        <button type="submit" class="save"><i class="fa fa-upload" aria-hidden="true"></i> Submit</button>
    </form>
{% endblock %}

myrestaurants/templates/myrestaurants/restaurant_detail.html
{% extends "myrestaurants/base.html" %}
{% block content %}
<h1>
    <i class="fa fa-cutlery" aria-hidden="true"></i> {{ restaurant.name }}
    {% if user == restaurant.user %}
      <div class="pullright">
        <a href="{% url 'myrestaurants:restaurant_edit' restaurant.id %}">
          <i class="fa fa-edit" aria-hidden="true"></i> edit</a>
      </div>
    {% endif %}
</h1>
<hr>
<div class="_d">
<h2><i class="fa fa-map-marker" aria-hidden="true"></i> Address:</h2>
<p>
    {{ restaurant.street }}, {{ restaurant.number }} <br/>
    {{ restaurant.zipcode }} {{ restaurant.city }} <br/>
    {{ restaurant.stateOrProvince }} ({{ restaurant.country }})
</p>

<h2>
    Dishes
    {% if user %}
    <div class="pullright _bd">
      <a href="{% url 'myrestaurants:dish_create' restaurant.id %}">
          <i class="fa fa-plus" aria-hidden="true"></i> add</a>
    </div>
    {% endif %}
</h2>
<ul class="_d_l">
    {% for dish in restaurant.dishes.all %}
        <li>
          <i class="fa fa-check-square-o" aria-hidden="true"></i>
          <a href="{% url 'myrestaurants:dish_detail' restaurant.id dish.id %}">
            {{ dish.name }}
          </a>
        </li>
    {% empty %}<li>Sorry, no dishes for this restaurant yet.</li>
    {% endfor %}
</ul>
<div class="boxijo">
<h2>Reviews</h2>
</div>
<ul class="review">
    {% for review in restaurant.restaurantreview_set.all %}
        <li>
            <p>{{ review.rating }} star{{ review.rating|pluralize }}</p>
            <p>{{ review.comment }}</p>
            <p class="waktu">Created by {{ review.user }} on {{ review.date }}</p>
        </li>
    {% endfor %}
</ul>
<div class="br__">
<h2>Add Review</h2>
</div>
<form action="{% url 'myrestaurants:review_create' restaurant.id %}" method="post" class="_f_i">
    {% csrf_token %}
    <textarea name="comment" id="comment" placeholder="Message" class="_r_m"></textarea>
    <p><span  class="_r_r">Rating :</span>
      <span class="star-rating star">
        {% for rate in RATING_CHOICES %}
        <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" /><i></i>
        {% endfor %}
      </span>
    </p>
    <button type="submit" class="_rsave"><i class="fa fa-upload" aria-hidden="true"></i> Review</button>
</form>
</div>
{% endblock %}
{% block footer %}
    Created by {{ restaurant.user }} on {{ restaurant.date }}
{% endblock %}

myrestaurants/templates/myrestaurants/restaurant_list.html
{% extends "myrestaurants/base.html" %}
{% block content %}
<h1>
    <i class="fa fa-cutlery" aria-hidden="true"></i> Restaurants
    {% if user %}
      <div class="pullright">
        <a href="{% url 'myrestaurants:restaurant_create' %}"><i class="fa fa-plus" aria-hidden="true"></i> add</a>
      </div>
    {% endif %}
</h1>
<hr>
<ul class="list">
    {% for restaurant in latest_restaurant_list %}
        <li>
          <a href="{% url 'myrestaurants:restaurant_detail' restaurant.id %}">
            {{ restaurant.name }}
          </a>
        </li>
    {% empty %}
      <li>Sorry, no restaurants registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}